package(default_visibility = [
    "//src/main/java/com/zombiesatemy/tatamidoku:__subpackages__",
    "//src/test/java/com/zombiesatemy/tatamidoku:__subpackages__",
])

java_library(
    name = "game",
    srcs = glob(["*.java"]),
)
